[package]
name = "code-extract-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.9"
walkdir = "2"
regex = "1"
encoding_rs = "0.8"
encoding_rs_io = "0.1"
docx-rs = "0.4"
anyhow = "1"
rfd = "0.15"
ignore = "0.4"

[build-dependencies]
slint-build = "1.9"
